### ISSUE TITLE
Fails to build against Electron 1.4.15

### ISSUE THREAD

**Issue by morganrallen** [cheery/node-udev#16]
After a plain install it fails with `Module version mismatch.`

```
Uncaught Exception:
Error: Module version mismatch. Expected 50, got 47.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/******************************/node_modules/udev/udev.js:1:91)
```

Typically `electron-rebuild` can be used to rebuild against the present version of `electron`. This succeeds as expected but then the module mismatch results in a Fatal error.

```
#
# Fatal error in ../../v8/src/api.cc, line 1082
# Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
#

==== C stack trace ===============================

 1: V8_Fatal
 2: 0x7f3e6fef8ebd
 3: 0x7f3e5cd16234
 4: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: 0x7f3e6ff57b91
 7: 0x7f3e6ff7e60f
 8: 0x2b19d7306147
```

This is all I have for now, trying to figure out how to get a better stack trace.

**Comment by cheery** [comment]
Well done, @morganrallen
